<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class PeralatanSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // Perlengkapan Makan (Untuk Siswa)
            [
                'sku' => 'PMK-001',
                'name' => 'Ompreng / Kotak Makan Stainless Steel (5 Sekat)',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pcs',
                'stock' => 500,
                'reorder_point' => 50,
                'max_stock' => 1000,
                'unit_price' => 35000,
                'supplier' => 'PT Makmur Logistik Perkakas',
                'notes' => 'Kotak makan anti karat dengan tutup rapat untuk distribusi makanan.',
            ],
            [
                'sku' => 'PMK-002',
                'name' => 'Set Sendok & Garpu Stainless',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pasang',
                'stock' => 600,
                'reorder_point' => 100,
                'max_stock' => 1200,
                'unit_price' => 5000,
                'supplier' => 'PT Makmur Logistik Perkakas',
                'notes' => 'Alat makan untuk siswa.',
            ],
            [
                'sku' => 'PMK-003',
                'name' => 'Gelas Tumbler Plastik BPA Free (300ml)',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pcs',
                'stock' => 500,
                'reorder_point' => 50,
                'max_stock' => 1000,
                'unit_price' => 8000,
                'supplier' => 'Toko Alat Tulis & Plastik Maju',
                'notes' => 'Untuk jatah air minum/susu anak.',
            ],
            [
                'sku' => 'PMK-004',
                'name' => 'Piring Stainless Steel Besar',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pcs',
                'stock' => 400,
                'reorder_point' => 50,
                'max_stock' => 800,
                'unit_price' => 12000,
                'supplier' => 'PT Makmur Logistik Perkakas',
                'notes' => 'Piring stainless anti karat untuk siswa.',
            ],
            [
                'sku' => 'PMK-005',
                'name' => 'Sendok Sayur Stainless Besar',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pcs',
                'stock' => 20,
                'reorder_point' => 5,
                'max_stock' => 30,
                'unit_price' => 15000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk menyendok sup/sayur porsi besar.',
            ],
            [
                'sku' => 'PMK-006',
                'name' => 'Nampan / Tray Plastik (40x30 cm)',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pcs',
                'stock' => 200,
                'reorder_point' => 30,
                'max_stock' => 400,
                'unit_price' => 18000,
                'supplier' => 'PT Makmur Logistik Perkakas',
                'notes' => 'Untuk membawa kotak makan siswa saat distribusi.',
            ],
            [
                'sku' => 'PMK-007',
                'name' => 'Sumpit Kayu Sekali Pakai (1 pak = 100 pasang)',
                'category' => 'Perlengkapan Makan',
                'unit' => 'pak',
                'stock' => 10,
                'reorder_point' => 3,
                'max_stock' => 20,
                'unit_price' => 12000,
                'supplier' => 'Toko Peralatan Makan Murah',
                'notes' => 'Cadangan alat makan sekali pakai.',
            ],

            // Peralatan Dapur (Untuk Memasak)
            [
                'sku' => 'PDR-001',
                'name' => 'Dandang Nasi Besar (Kapasitas 20 Liter)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 4,
                'reorder_point' => 1,
                'max_stock' => 6,
                'unit_price' => 450000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Digunakan untuk menanak nasi porsi besar.',
            ],
            [
                'sku' => 'PDR-002',
                'name' => 'Wajan Penggorengan Besar (Diameter 80cm)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 3,
                'reorder_point' => 1,
                'max_stock' => 5,
                'unit_price' => 320000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk menumis/menggoreng lauk massal.',
            ],
            [
                'sku' => 'PDR-003',
                'name' => 'Spatula Kayu Super Besar (Sutil Aduk)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 6,
                'reorder_point' => 2,
                'max_stock' => 10,
                'unit_price' => 35000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Kayu mahoni untuk mengaduk kuali masakan.',
            ],
            [
                'sku' => 'PDR-004',
                'name' => 'Panci Sup Kuah (Kapasitas 30 Liter)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 3,
                'reorder_point' => 1,
                'max_stock' => 5,
                'unit_price' => 280000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk sayur sop/lodeh dll.',
            ],
            [
                'sku' => 'PDR-005',
                'name' => 'Tabung Gas Elpiji 12 Kg (Isi Ulang)',
                'category' => 'Peralatan Dapur',
                'unit' => 'tabung',
                'stock' => 8,
                'reorder_point' => 3,
                'max_stock' => 12,
                'unit_price' => 220000,
                'supplier' => 'Agen LPG Pak Kumis',
                'notes' => 'Stok gas untuk operasional kompor besar.',
            ],
            [
                'sku' => 'PDR-006',
                'name' => 'Kompor Gas Industri 2 Tungku',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 2,
                'reorder_point' => 1,
                'max_stock' => 4,
                'unit_price' => 1200000,
                'supplier' => 'Toko Peralatan Memasak Industri',
                'notes' => 'Kompor bertenaga besar untuk memasak massal.',
            ],
            [
                'sku' => 'PDR-007',
                'name' => 'Talenan Plastik HDPE Tebal (50x30 cm)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 8,
                'reorder_point' => 2,
                'max_stock' => 15,
                'unit_price' => 65000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Anti bakteri, untuk memotong daging & sayur.',
            ],
            [
                'sku' => 'PDR-008',
                'name' => 'Pisau Dapur Stainless Chef Knife',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 10,
                'reorder_point' => 3,
                'max_stock' => 20,
                'unit_price' => 55000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Pisau serbaguna untuk dapur umum.',
            ],
            [
                'sku' => 'PDR-009',
                'name' => 'Saringan / Strainer Stainless Besar',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 5,
                'reorder_point' => 2,
                'max_stock' => 10,
                'unit_price' => 45000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk meniriskan nasi, mie, atau sayuran rebus.',
            ],
            [
                'sku' => 'PDR-010',
                'name' => 'Baskom Plastik Besar (Diameter 60 cm)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 10,
                'reorder_point' => 3,
                'max_stock' => 20,
                'unit_price' => 35000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk mencuci sayur, merendam bahan baku dll.',
            ],
            [
                'sku' => 'PDR-011',
                'name' => 'Wadah Penyimpanan Makanan Bertutup (10 Liter)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 20,
                'reorder_point' => 5,
                'max_stock' => 40,
                'unit_price' => 25000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk menyimpan bumbu, sisa lauk, dll.',
            ],
            [
                'sku' => 'PDR-012',
                'name' => 'Rak Stainless Gudang Bahan Baku (5 Tingkat)',
                'category' => 'Peralatan Dapur',
                'unit' => 'unit',
                'stock' => 3,
                'reorder_point' => 1,
                'max_stock' => 5,
                'unit_price' => 850000,
                'supplier' => 'PT Rak Serbaguna Indonesia',
                'notes' => 'Rak penyimpanan bahan baku di gudang dapur.',
            ],
            [
                'sku' => 'PDR-013',
                'name' => 'Timbangan Digital Dapur (Kapasitas 30 Kg)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 2,
                'reorder_point' => 1,
                'max_stock' => 4,
                'unit_price' => 350000,
                'supplier' => 'PT Timbangan Akurat',
                'notes' => 'Untuk menimbang bahan baku secara akurat.',
            ],
            [
                'sku' => 'PDR-014',
                'name' => 'Blender Komersil / Jus (2 Liter)',
                'category' => 'Peralatan Dapur',
                'unit' => 'pcs',
                'stock' => 2,
                'reorder_point' => 1,
                'max_stock' => 4,
                'unit_price' => 450000,
                'supplier' => 'Toko Peralatan Memasak Industri',
                'notes' => 'Untuk menghaluskan bumbu/jus buah.',
            ],
            [
                'sku' => 'PDR-015',
                'name' => 'Cobek Batu / Ulekan Besar',
                'category' => 'Peralatan Dapur',
                'unit' => 'set',
                'stock' => 4,
                'reorder_point' => 1,
                'max_stock' => 8,
                'unit_price' => 120000,
                'supplier' => 'Pasar Tradisional',
                'notes' => 'Untuk menghaluskan bumbu secara tradisional.',
            ],

            // Perlengkapan Pengemasan & Distribusi
            [
                'sku' => 'PKM-001',
                'name' => 'Kantong Plastik Ziplock (1 pak = 100 pcs)',
                'category' => 'Lainnya',
                'unit' => 'pak',
                'stock' => 20,
                'reorder_point' => 5,
                'max_stock' => 50,
                'unit_price' => 15000,
                'supplier' => 'Toko Plastik Serba Ada',
                'notes' => 'Untuk membungkus makanan cadangan.',
            ],
            [
                'sku' => 'PKM-002',
                'name' => 'Sarung Tangan Plastik Sekali Pakai (1 pak = 100 pcs)',
                'category' => 'Lainnya',
                'unit' => 'pak',
                'stock' => 15,
                'reorder_point' => 5,
                'max_stock' => 30,
                'unit_price' => 20000,
                'supplier' => 'Toko Plastik Serba Ada',
                'notes' => 'Untuk higienitas saat membagikan makanan.',
            ],
            [
                'sku' => 'PKM-003',
                'name' => 'Penutup Saji / Tudung Saji Besar',
                'category' => 'Lainnya',
                'unit' => 'pcs',
                'stock' => 10,
                'reorder_point' => 3,
                'max_stock' => 20,
                'unit_price' => 35000,
                'supplier' => 'Toko Perlengkapan Dapur Sentosa',
                'notes' => 'Untuk menutup makanan saat distribusi.',
            ],
            [
                'sku' => 'PKM-004',
                'name' => 'Kertas Minyak / Parchment Paper (1 roll = 50m)',
                'category' => 'Lainnya',
                'unit' => 'roll',
                'stock' => 10,
                'reorder_point' => 3,
                'max_stock' => 20,
                'unit_price' => 25000,
                'supplier' => 'Toko Plastik Serba Ada',
                'notes' => 'Alas piring atau pembungkus lauk.',
            ],

            // Perlengkapan Kebersihan & Higienitas
            [
                'sku' => 'CLN-001',
                'name' => 'Sabun Cuci Piring Jerigen (5 Liter)',
                'category' => 'Lainnya',
                'unit' => 'jerigen',
                'stock' => 5,
                'reorder_point' => 2,
                'max_stock' => 10,
                'unit_price' => 45000,
                'supplier' => 'Toko Sabun Bersih Kilau',
                'notes' => 'Pembersih utama untuk mencuci ratusan ompreng.',
            ],
            [
                'sku' => 'CLN-002',
                'name' => 'Spons Cuci Piring Sabut Kasar',
                'category' => 'Lainnya',
                'unit' => 'pcs',
                'stock' => 20,
                'reorder_point' => 5,
                'max_stock' => 40,
                'unit_price' => 4000,
                'supplier' => 'Toko Sabun Bersih Kilau',
                'notes' => 'Barang habis pakai bulanan.',
            ],
            [
                'sku' => 'CLN-003',
                'name' => 'Celemek (Apron) Dapur PVC Anti Air',
                'category' => 'Lainnya',
                'unit' => 'pcs',
                'stock' => 10,
                'reorder_point' => 2,
                'max_stock' => 15,
                'unit_price' => 25000,
                'supplier' => 'Toko Seragam Konveksi',
                'notes' => 'Untuk petugas cuci piring dan koki.',
            ],
            [
                'sku' => 'CLN-004',
                'name' => 'Karbol / Cairan Disinfektan Lantai (5 Liter)',
                'category' => 'Lainnya',
                'unit' => 'jerigen',
                'stock' => 6,
                'reorder_point' => 2,
                'max_stock' => 15,
                'unit_price' => 35000,
                'supplier' => 'Toko Sabun Bersih Kilau',
                'notes' => 'Untuk kebersihan lantai area dapur umum.',
            ],
            [
                'sku' => 'CLN-005',
                'name' => 'Sapu & Pengki Set (Dapur)',
                'category' => 'Lainnya',
                'unit' => 'set',
                'stock' => 5,
                'reorder_point' => 1,
                'max_stock' => 10,
                'unit_price' => 30000,
                'supplier' => 'Toko Peralatan Kebersihan',
                'notes' => 'Untuk menyapu area dapur dan ruang distribusi.',
            ],
            [
                'sku' => 'CLN-006',
                'name' => 'Ember Plastik Bertutup (20 Liter)',
                'category' => 'Lainnya',
                'unit' => 'pcs',
                'stock' => 8,
                'reorder_point' => 2,
                'max_stock' => 15,
                'unit_price' => 22000,
                'supplier' => 'Toko Peralatan Kebersihan',
                'notes' => 'Untuk menampung air cucian / sampah organik.',
            ],
            [
                'sku' => 'CLN-007',
                'name' => 'Masker Kain Dapur (1 pak = 50 pcs)',
                'category' => 'Lainnya',
                'unit' => 'pak',
                'stock' => 5,
                'reorder_point' => 2,
                'max_stock' => 10,
                'unit_price' => 30000,
                'supplier' => 'Toko Seragam Konveksi',
                'notes' => 'Untuk higienitas petugas dapur.',
            ],
            [
                'sku' => 'CLN-008',
                'name' => 'Topi Koki / Hairnet Jaring (1 pak = 50 pcs)',
                'category' => 'Lainnya',
                'unit' => 'pak',
                'stock' => 5,
                'reorder_point' => 2,
                'max_stock' => 10,
                'unit_price' => 20000,
                'supplier' => 'Toko Seragam Konveksi',
                'notes' => 'Untuk mencegah rambut jatuh ke makanan.',
            ],
        ];

        foreach ($items as $item) {
            InventoryItem::updateOrCreate(
                ['sku' => $item['sku']],
                $item
            );
        }

        $total = count($items);
        $this->command->info("✅ {$total} peralatan & perlengkapan dapur berhasil di-seed.");
    }
}
